 
all:
	g++ --std=c++11 -I/usr/include/cryptopp main.cpp -o desafio6 -lgmp -lm -lcryptopp

gdb:
	g++ --std=c++11 -I/usr/include/cryptopp -ggdb main.cpp -o desafio6 -lgmp -lm -lcryptopp

clean: 
	rm *.o main
